<a href="https://colab.research.google.com/github/selvaganapathy18/Fdva/blob/main/fdva_exp_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df_csv = pd.read_csv("data1.csv")
df_csv.head()

      Name  Age  Gender  Marks Department
0     Arun   20    Male     85        CSE
1    Priya   21  Female     92        ECE
2  Karthik   20    Male     78         IT
3    Divya   22  Female     88        CSE
4    Rahul   21    Male     75        EEE

In [ ]:
import pandas as pd

df_excel = pd.read_excel(
    "data2.xlsx",
        sheet_name="Sheet1",
            engine="openpyxl"
            )

df_excel.head()

   Year  Temperature  Investment   GDP  Population
0  2015         28.5         120  2100        1350
1  2016         29.1         135  2250        1370
2  2017         29.8         150  2400        1390
3  2018         30.2         175  2580        1410
4  2019         30.5         190  2750        1430

In [ ]:
import requests
from io import StringIO

url="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"


headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}


response = requests.get(url, headers=headers)
html_content = response.text


tables = pd.read_html(StringIO(html_content))
df_web = tables[2]
df_web.head()

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,100834796
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211

In [ ]:
df=pd.read_excel("/content/data2.xlsx")
df.to_excel("/content/weeeeee.xlsx", index=False)
df.head()

   Year  Temperature  Investment   GDP  Population
0  2015         28.5         120  2100        1350
1  2016         29.1         135  2250        1370
2  2017         29.8         150  2400        1390
3  2018         30.2         175  2580        1410
4  2019         30.5         190  2750        1430